name: search/sr/10
seed: 1

log_level: info
report_interval: 10
eval_interval: 50
save_interval: 50
eval_multi: True

data_path: data/sr
train_sets:
  - name: "10"
    samples: 2000
    max_tries: 5
    max_flips: 200
    iterations: 10000

eval_set:
  name: "25"
  samples: 10
  max_tries: 25
  max_flips: 400

model_path: results/search/sr/5/model_best.pth

gnn_hidden_size: 32
gnn_iter: 2
gnn_async: False
readout_hidden_size: 64

mlp_arch:
  hidden_sizes: [32]
  activation: ReLU

cycles: 1
optimizer: RMSprop
lr: 0.0001
lr_milestones: [10000]
lr_decay: 0.8

method: reinforce
discount: 0.25
walk_prob: 0.5
